docs_dir: docs

site_name: atomea
site_author: Scientific Computing Studio

# Git host
repo_name: scienting/atomea
repo_url: https://github.com/scienting/atomea

# https://squidfunk.github.io/mkdocs-material/
theme:
  name: material
  custom_dir: docs/.overrides
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: dark
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    annotation: material/star-four-points-circle
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - navigation.path
    - navigation.prune
    - toc.follow
    - search.suggest

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

# Options need to be indented twice for some reason?
plugins:
  - search
  - autorefs
  - material-plausible
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - mkdocstrings:
      handlers:
        python:
          inventories:
            - "https://docs.python.org/3/objects.inv"
            - "https://numpy.org/doc/stable/objects.inv"
            - "https://docs.pola.rs/py-polars/html/objects.inv"
            - "https://zarr.readthedocs.io/en/stable/objects.inv"
          paths: ["atomea"]
          options:
            annotations_path: brief
            docstring_style: google
            docstring_section_style: spacy
            show_if_no_docstring: true
            show_docstring_yields: true
            show_docstring_examples: true
            show_docstring_raises: true
            show_root_toc_entry: true
            show_root_full_path: true
            show_object_full_path: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_members_full_path: true
            show_source: false
            merge_init_into_class: true
            line_length: 88
            show_root_heading: false
            find_stubs_package: true
  - awesome-nav
  - glightbox
  - macros
  - git-revision-date-localized:
      type: iso_datetime
      timezone: America/Detroit
      fallback_to_build_date: true

extra:
  generator: false
  analytics:
    provider: plausible
    domain: atomea.scient.ing

extra_css:
  - css/base.css
  - css/colors.css
  - css/mkdocstrings.css

extra_javascript:
  - js/mathjax-config.js
  - js/d3.js

markdown_extensions:
  - abbr
  - toc:
      permalink: true
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
