[project]
name = "atomea"
description = "A hierarchical data model for atomistic systems"
authors = [
    "Scientific Computing Studio <us@scient.ing>",
]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]
license = "Apache-2.0"
readme = "README.md"

[pypi-dependencies]
atomea = { path = ".", editable = true }

[environments]
dev = ["dev"]
docs = ["docs"]

[tasks]
uuid = 'python -c "import uuid; print(uuid.uuid4())"'

[dependencies]
python = ">=3.12"
loguru = ">=0.7.2,<1"
numpy = ">=1.2.6,<3"
pydantic = ">=2.10.6,<3"
pyyaml = ">=6.0.2,<7"
zarr = ">=3.0.0,<4"
polars = ">=1.10.0,<2"

[feature.dev.dependencies]
black = ">=23.10.0"
isort = ">=5.12.0"
pylint = ">=3.0.1"
mypy = ">=1.6.0"
pytest = ">=7.4.2"
pytest-cov = ">=4.1.0"
coverage = ">=7.3.1"
pytest-html = ">=4.0.1"
colorama = ">=0.4.6"
mdanalysis = ">=2.8.0,<3"
basedpyright = ">=1.29.1,<2"
ruff = ">=0.11.9,<0.12"
twine = ">=6.1.0,<7"

[feature.dev.tasks]
mdlint = { cmd = ["markdownlint-cli2", '"docs/*.{md,markdown}"', "--fix", "--config", ".markdownlint.yaml", "||", "true"] }
isort = { cmd = ["isort", "--settings-path", ".isort.cfg", "./atomea", "./tests", "||", "true"] }
ruff = { cmd = ["ruff", "format", "--config", ".ruff.toml", "./atomea", "./tests", "||", "true"] }
format = { depends-on = ["mdlint", "isort", "ruff"] }
data = { cmd = ["rm", "-rf", "tests/files", "&&", "git", "clone", "git@github.com:scienting/atomea-data.git", "tests/files"]}
tests = { cmd = [
    "PYTHONPATH=.",
    "pytest",
    "-c",
    ".pytest.ini",
    "--cov='atomea'",
    "--cov-report=xml",
    "--junit-xml=report.xml",
    "--failed-first",
]}
coverage = { cmd = ["coverage", "report"] }
cleanup-build = { cmd = ["rm", "-rf", "./build"] }
build = { cmd = ["python3", "-m", "build"], depends-on = ["cleanup-build"]}
publish-test = { cmd = ["twine", "upload", "--repository", "testpypi", "dist/*"] }
publish = { cmd = ["twine", "upload", "dist/*"] }

[feature.dev.pypi-dependencies]
build = ">=1.2.2.post1,<2"
mypy-extensions = ">=1.0.0"
pyrefly = ">=0.16.0, <0.17"
setuptools-scm = ">=8.0.0"

[feature.docs.dependencies]
mkdocs = ">=1.6.1,<2"
mkdocs-material = ">=9.6.5,<10"
mkdocstrings = ">=0.28.2,<0.29"
mkdocstrings-python = ">=1.16.2,<2"
pymdown-extensions = ">=10.14.3,<11"
mkdocs-table-reader-plugin = ">=3.1.0,<4"
mkdocs-gen-files = ">=0.4.0,<0.5"
mkdocs-macros-plugin = ">=1.3.7,<2"
mkdocs-glightbox = ">=0.4.0,<0.5"
mkdocs-git-revision-date-localized-plugin = ">=1.2.9,<2"

[feature.docs.pypi-dependencies]
material-plausible-plugin = ">=0.2.0, <0.3"
mkdocs-print-site-plugin = ">=2.6.0, <3"
mkdocs-awesome-nav = ">=3.0.0, <4"

[feature.docs.tasks]
docs = { cmd = ["rm", "-rf", "./public/", "&&", "mkdocs", "build", "-d", "public/"] }
serve = { cmd = ["mkdocs", "serve"] }
