nav:
    - Home: index.md
    - Containers:
      - containers/index.md
      - Levels:
        - containers/levels/index.md
        - Project: containers/levels/project.md
        - Ensemble: containers/levels/ensemble.md
        - Microstate: containers/levels/microstate.md
      - UUIDs: containers/uuids.md
      - Design:
        - containers/design/index.md
        - Energy: containers/design/energy.md
        - Quantum: containers/design/quantum.md
        - Time: containers/design/time.md
        - Topology: containers/design/topology.md
    - IO:
      - io/index.md
      - Readers:
        - io/readers/index.md
      - Writers:
        - io/writers/index.md
    - Examples:
      - examples/index.md
    - API: api

sort:
  type: natural
  ignore_case: true
  by: title
  direction: asc
flatten_single_child_sections: true
